from .storyboard_assembler import NODE_CLASS_MAPPINGS as STORYBOARD_NODES, NODE_DISPLAY_NAME_MAPPINGS as STORYBOARD_NAMES
from .simple_gate import NODE_CLASS_MAPPINGS as GATE_NODES, NODE_DISPLAY_NAME_MAPPINGS as GATE_NAMES
from .extract_first_frame import NODE_CLASS_MAPPINGS as FRAME_NODES, NODE_DISPLAY_NAME_MAPPINGS as FRAME_NAMES
from .threeshot import NODE_CLASS_MAPPINGS as THREESHOT_NODES, NODE_DISPLAY_NAME_MAPPINGS as THREESHOT_NAMES
from .threeshot_simple import NODE_CLASS_MAPPINGS as THREESHOT_SIMPLE_NODES, NODE_DISPLAY_NAME_MAPPINGS as THREESHOT_SIMPLE_NAMES
from .image_concat_multi import NODE_CLASS_MAPPINGS as CONCAT_NODES, NODE_DISPLAY_NAME_MAPPINGS as CONCAT_NAMES
from .list_to_batch import NODE_CLASS_MAPPINGS as LIST_NODES, NODE_DISPLAY_NAME_MAPPINGS as LIST_NAMES
from .scene_camera import NODE_CLASS_MAPPINGS as SCENE_CAMERA_NODES, NODE_DISPLAY_NAME_MAPPINGS as SCENE_CAMERA_NAMES
from .show_text import NODE_CLASS_MAPPINGS as SHOW_TEXT_NODES, NODE_DISPLAY_NAME_MAPPINGS as SHOW_TEXT_NAMES

NODE_CLASS_MAPPINGS = {**STORYBOARD_NODES, **GATE_NODES, **FRAME_NODES, **THREESHOT_NODES, **THREESHOT_SIMPLE_NODES, **CONCAT_NODES, **LIST_NODES, **SCENE_CAMERA_NODES, **SHOW_TEXT_NODES}
NODE_DISPLAY_NAME_MAPPINGS = {**STORYBOARD_NAMES, **GATE_NAMES, **FRAME_NAMES, **THREESHOT_NAMES, **THREESHOT_SIMPLE_NAMES, **CONCAT_NAMES, **LIST_NAMES, **SCENE_CAMERA_NAMES, **SHOW_TEXT_NAMES}

WEB_DIRECTORY = "./js"

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
