"""
SoraUtils Preset Lists
Centralized preset definitions for all shot parameters.
"""

CAMERA_MOTIONS = [
    "static (locked off)",
    "slow push in",
    "slow pull out",
    "dolly forward",
    "dolly backward",
    "dolly left to right",
    "dolly right to left",
    "truck left",
    "truck right",
    "pedestal up (crane rise)",
    "pedestal down (crane lower)",
    "boom up",
    "boom down",
    "pan left",
    "pan right",
    "slow pan left",
    "slow pan right",
    "whip pan left",
    "whip pan right",
    "tilt up",
    "tilt down",
    "slow tilt up",
    "slow tilt down",
    "orbit clockwise",
    "orbit counterclockwise",
    "slow orbit clockwise",
    "slow orbit counterclockwise",
    "arc left around subject",
    "arc right around subject",
    "zoom in (lens zoom)",
    "zoom out (lens zoom)",
    "slow zoom in",
    "slow zoom out",
    "crash zoom in",
    "dolly zoom (vertigo effect)",
    "handheld (subtle drift)",
    "handheld (shaky, urgent)",
    "steadicam follow",
    "steadicam lead (walking backward)",
    "tracking alongside subject",
    "tracking behind subject",
    "drone ascending",
    "drone descending",
    "drone flyover",
    "drone fly-through",
    "roll clockwise (Dutch roll)",
    "roll counterclockwise (Dutch roll)",
    "jib arm sweep",
    "cable cam glide",
    "first-person POV movement",
    "360 rotation around subject",
]

CAMERA_SHOT_TYPES = [
    "extreme wide shot (EWS)",
    "wide shot / establishing shot",
    "full shot (head to toe)",
    "medium wide shot (cowboy / 3/4)",
    "medium shot (waist up)",
    "medium close-up (chest up)",
    "close-up (face)",
    "extreme close-up (eyes / detail)",
    "insert shot (object detail)",
    "over-the-shoulder (OTS)",
    "two-shot",
    "three-shot (group)",
    "POV (first person)",
    "low angle (looking up)",
    "high angle (looking down)",
    "bird's eye (top down)",
    "worm's eye (ground level up)",
    "Dutch angle (tilted)",
    "profile shot (side view)",
    "silhouette shot",
    "through-frame (foreground obstruction)",
    "deep focus (everything sharp)",
    "shallow focus (subject isolated)",
    "rack focus (shift between planes)",
    "split diopter (dual focus)",
    "long lens compressed (telephoto)",
    "wide angle distorted (fisheye)",
    "macro (extreme detail)",
    "aerial shot",
    "underwater shot",
    "reflection shot (mirror / water)",
    "framed shot (doorway / window)",
]

LIGHTING_STYLES = [
    "natural daylight",
    "golden hour (warm sunset)",
    "blue hour (cool twilight)",
    "overcast (soft diffused)",
    "harsh midday sun",
    "dappled light (through trees/blinds)",
    "moonlight (cool blue ambient)",
    "candlelight (warm flicker)",
    "firelight (warm orange flicker)",
    "neon (colorful, urban)",
    "fluorescent (cool, flat, institutional)",
    "tungsten (warm practical bulbs)",
    "chiaroscuro (high contrast, dramatic)",
    "Rembrandt lighting (triangle on cheek)",
    "split lighting (half face lit)",
    "butterfly lighting (glamour, from above)",
    "rim lighting (edge-lit silhouette)",
    "backlit (subject in shadow, halo edge)",
    "silhouette (full backlight, no fill)",
    "low-key (mostly shadow, moody)",
    "high-key (bright, minimal shadow)",
    "volumetric (god rays, haze, fog)",
    "spotlight (pool of light)",
    "ambient bounce (soft reflected)",
    "mixed practical sources",
    "LED panel (clean, even)",
    "strobe / flash (frozen, crisp)",
    "noir (venetian blind shadows)",
    "color gel (stylized color wash)",
    "bioluminescent (eerie glow)",
    "emergency lighting (red alarm)",
    "screen glow (computer / phone light)",
    "stage lighting (theatrical spots)",
    "car headlights",
    "underwater caustics",
    "lightning flash (intermittent)",
]

COLOR_GRADING_PRESETS = [
    "natural / neutral",
    "warm golden tones",
    "cool blue tones",
    "teal and orange (blockbuster)",
    "desaturated muted",
    "high contrast punchy",
    "film noir (black & white)",
    "cross-processed (shifted hues)",
    "bleach bypass (low sat, high contrast)",
    "vintage film stock (grain + faded blacks)",
    "cyberpunk neon (saturated magentas & cyans)",
    "pastel soft (lifted shadows, low contrast)",
    "muted earth tones",
    "monochrome sepia",
    "day-for-night (blue push, crushed shadows)",
    "orange and teal inverted",
    "analog VHS (soft, color bleed)",
    "Kodak Portra (warm skin, muted greens)",
    "Fuji Velvia (saturated landscape, rich blues)",
    "LOG flat (ungraded, maximum latitude)",
]

MOOD_PRESETS = [
    "serene / peaceful",
    "tense / suspenseful",
    "joyful / uplifting",
    "melancholic / somber",
    "dramatic / intense",
    "mysterious / enigmatic",
    "romantic / intimate",
    "epic / grand",
    "eerie / unsettling",
    "playful / whimsical",
    "raw / gritty",
    "dreamy / ethereal",
    "nostalgic / wistful",
    "chaotic / frantic",
    "contemplative / still",
    "ominous / foreboding",
    "triumphant / victorious",
    "lonely / isolated",
    "sacred / reverent",
    "absurd / surreal",
]
